### ISSUE TITLE
Doesn't seem to take fifth clue into account properly.

### ISSUE THREAD

**Issue by Sbrikky** [Chris1712/wordle-solver#1]
With the following first 4 guesses, it says 6 words remaining and with the suggested guess being 'agnew':
![image](https://user-images.githubusercontent.com/15995601/149355873-f0cd8831-d27b-47b2-b8b2-2e35c05e295c.png)

Then when I put in my fifth guess 'adage' it doesn't update the remaining words and keeps suggesting agnew. even though adage has a "g" in a "b" slot so agnew is definitely wrong:
![image](https://user-images.githubusercontent.com/15995601/149356155-0daf9ce4-5cd6-4b83-a6a2-450ae3ebb8c5.png)

**Comment by Sbrikky** [comment]
Maybe related, but manage to have it not update properly after the third guess. I was filling it in as if the word I was guessing was Quake:
![image](https://user-images.githubusercontent.com/15995601/149358524-413690a0-51b8-42de-a959-8315f58211ea.png)

**Comment by Sbrikky** [comment]
Maybe if there are no words left in the word list it doesn't update?

**Comment by Chris1712** [comment]
Yeah I think you're right. The logic for eliminating words using the supplied answers doesn't handle words like 'adage' where letters are repeated but with different answers - when we get that first 'a' as black, all words with a in are eliminated. And the second 'a' with green eliminates all words without a's.

**Comment by Chris1712** [comment]
Good news: this is fixed.
Bad news: the old guessing performance (which was totally broken) did tend to be faster. I've exacerbated this by adding a larger and more correct dictionary. :man_shrugging: 
Efficiency gains are now to be found in `pickBestGuessFromList` which is totally janks
