### ISSUE TITLE
Solver gives impossible suggestions

### ISSUE THREAD

**Issue by Sbrikky** [Chris1712/wordle-solver#3]
With these two first guesses and the word being "Tangy" it suggests Guano, eventhough the first letter G is a Y, so it can't be Guano.
![image](https://user-images.githubusercontent.com/15995601/149489877-11e65fdb-d414-48df-9a3b-d7ce13f7021b.png)
If you then fill in Guano, it suggests Whang, so it moves the G properly, but keeps the Yellow A and N in the same place.
![image](https://user-images.githubusercontent.com/15995601/149489965-90d601b6-04ce-46aa-92ce-22fb708e405c.png)
If you then fill in Whang it suggests Kyang, which keeps the Yellow ANG
![image](https://user-images.githubusercontent.com/15995601/149490149-688692f3-f7be-409e-a095-7ed254fffa64.png)
If you fill in Kyang it suggests Gandy, which finally moves the A, N, and Y into the correct place, but it moves the G back to the already yellow first spot
![image](https://user-images.githubusercontent.com/15995601/149490370-31d0ce72-c43b-4f96-8a99-b39b3b84f1f3.png)

**Comment by Chris1712** [comment]
I had very poor test coverage here! The bug was not so hard to figure out as I expected https://github.com/Chris1712/wordle-solver/commit/da434a3a3bb2250150578a4677f0abb1b91d813a :flushed:
